### ISSUE TITLE
slow content loading

### ISSUE THREAD

**Issue by Sicer** [acvigue/JellyfinPlayer#3] opened 2021-05-22 18:37 UTC
When I open or navigate through the different sections of the app, it takes more than 15 seconds to load the covers, from the web browser, this does not happen to me.

**Comment by acvigue** [comment] 2021-05-22 18:38
What is the client device & what is the server version?

**Comment by Sicer** [comment] 2021-05-22 18:39
Iphone X, version 14.5.1

**Comment by acvigue** [comment] 2021-05-22 18:42
I'm seeing a couple errors from your device and it's the only one reporting those. Could you try restarting your device or force closing all other apps? It seems to be a memory issue.
<img width="1961" alt="Screen Shot 2021-05-22 at 2 42 03 PM" src="https://user-images.githubusercontent.com/34462061/119237645-e0791c80-bb0b-11eb-99c5-c9f16e8cfb6f.png">

**Comment by Sicer** [comment] 2021-05-22 18:44
ok, i'm going to restart the iphone and load the app again without any other app open

**Comment by Sicer** [comment] 2021-05-22 18:45
I just tried and the same thing happens, I have reported the error to you

**Comment by acvigue** [comment] 2021-05-22 18:46
please send me an email to acvigue@me.com with the server URL and a demo user/password so I can try to reproduce this on my end.

**Comment by Sicer** [comment] 2021-05-22 18:53
sent

**Comment by acvigue** [comment] 2021-05-22 18:53
thanks - just got it. password doesn't seem to work

**Comment by Sicer** [comment] 2021-05-22 18:55
can you try now?

**Comment by acvigue** [comment] 2021-05-22 18:56
works! thanks. I'll look into it

**Comment by acvigue** [comment] 2021-05-22 19:20
Please update your reverse proxy to support http 2.0

**Closed by acvigue** 2021-05-22 19:20 UTC
Labels: bug

**Comment by Sicer** [comment] 2021-05-22 19:23
Can you explain to me how that is done? Thank you

**Comment by acvigue** [comment] 2021-05-22 19:24
Sure! What reverse proxy are you running?

**Comment by Sicer** [comment] 2021-05-22 19:28
at first I think I do not have any proxy, the connection is the default of the operator.
everything is with the home network connection

**Comment by acvigue** [comment] 2021-05-22 19:30
If you do not have a reverse proxy installed in front of your Jellyfin server (such as nginx, traefik, etc) you will need to enable https directly in the Jellyfin dashboard to turn on HTTP/2. Turning this on allows the images to load at the same time, instead of one by one.

**Comment by acvigue** [comment] 2021-05-22 19:34
referenced issues:
https://sentry.io/share/issue/c8f60c1ec4714fc1832af544d207a09d/
https://sentry.io/share/issue/9c32eebadb0846f6a62938e79a6fb9ef/
https://sentry.io/share/issue/bfaf63becb654d1c9589a9e608979e7b/
https://sentry.io/share/issue/efa9c746d1f745f49e4b360f028ce628/

**Comment by Sicer** [comment] 2021-05-22 19:35
Even so, why only happens to me with this app? neither the official jellyfin app, nor plex does this to me,
also from time to time the app closes and I get the error of sending you a notification
